import { createApp } from "vue";
import App from "./App.vue";
import "./style.css";
import ElementPlus from "element-plus";
import { router } from "./router/index";
import { VueQueryPlugin } from "@tanstack/vue-query";
import "element-plus/dist/index.css";
const app = createApp(App);
app.use(ElementPlus);
app.use(router);
app.use(VueQueryPlugin);
app.mount("#app");
